# Generated by Django 6.1.1 on 2026-09-20 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('direccion', models.TextField(verbose_name='Dirección / Domicilio')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='Referencia de Ubicación')),
                ('aval_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Aval')),
                ('aval_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Aval')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_prestado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital Prestado')),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='% Interés')),
                ('monto_total_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total a Pagar')),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='DIARIO', max_length=10)),
                ('numero_cuotas', models.PositiveIntegerField(default=24, verbose_name='Número de Cuotas')),
                ('monto_cuota', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monto por Cuota')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('orden_visita', models.PositiveIntegerField(default=1, verbose_name='Orden en Ruta de Cobro')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('EN_MORA', 'En Mora'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.cliente')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['orden_visita'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Recibido')),
                ('mora_penalizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Mora / Penalización')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Registro')),
                ('anulado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observaciones / Promesa de Pago')),
                ('cobrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Zona')),
                ('cobrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='prestamos.ruta'),
        ),
    ]
