# Generated by Django 6.1.1 on 2026-09-20 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagocuota',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='aval_nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='aval_telefono',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='pagocuota',
            name='anulado',
        ),
        migrations.RemoveField(
            model_name='pagocuota',
            name='cobrador',
        ),
        migrations.RemoveField(
            model_name='pagocuota',
            name='mora_penalizacion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagocuota',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='capital_prestado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='frecuencia',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='DIARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto_total_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='numero_cuotas',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='orden_visita',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='porcentaje_interes',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='cobrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('GESTOR', 'Gestor / Cobrador'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('ZONAL', 'Zonal'), ('DISTRITAL', 'Distrital')], default='GESTOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ruta_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestores', to='prestamos.ruta')),
                ('superior_directo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('zona_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='prestamos.zona')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='prestamos.zona'),
        ),
    ]
