# Generated by Django 6.1.1 on 2026-09-21 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_zona_alter_cliente_options_alter_pagocuota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
